name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run

      - name: Upload Cypress test screenshots (optional)
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/

      - name: Upload Cypress test videos (optional)
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: cypress-test-results
          path: cypress/results/

      - name: Publish Test Results to GitHub UI
        uses: dorny/test-reporter@v1
        with:
          name: Cypress Tests
          path: cypress/results/*.xml
          reporter: mocha-junit
