name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests (individually)
        run: |
          mkdir -p cypress/results
          for file in cypress/e2e/*.cy.js; do
            filename=$(basename "$file" .js)
            echo "Running $filename"
            npx cypress run --spec "$file" \
              --reporter mocha-junit-reporter \
              --reporter-options "mochaFile=cypress/results/results-${filename}.xml" || exit 1
          done

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/

      - name: Upload Cypress test results
        uses: actions/upload-artifact@v4
        with:
          name: cypress-test-results
          path: cypress/results/

      - name: Publish Test Results to GitHub UI
        uses: dorny/test-reporter@v1
        with:
          name: Cypress Tests
          path: cypress/results/*.xml
          reporter: mocha-junit
          path-replace-backslashes: false
          list-suites: all
          list-tests: all
          max-annotations: 50
          fail-on-error: true
          fail-on-empty: true
          only-summary: false
